FROM python:3.12-slim

WORKDIR /app

COPY ../requirements.txt .
COPY ../requirements.dev.txt .

# Upgrade pip and install the dependencies
RUN pip3 install --upgrade pip && \
    pip3 install --no-cache-dir -r requirements.txt -r requirements.dev.txt

COPY ../tails_server ./tails_server
COPY ../bin ./bin
COPY ../README.md ./
COPY ../setup.py ./

# Install the application
RUN pip3 install --no-cache-dir -e .

ENTRYPOINT ["/bin/bash", "-c", "tails-server \"$@\""]

